parser: '@typescript-eslint/parser'
extends: standard
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - chai-friendly
rules:
  chai-friendly/no-unused-expressions: 2
  no-unused-expressions: 0